"""Nouvelles tables

Revision ID: a7e1c33a5eb3
Revises: b5d47a980d9c
Create Date: 2026-03-08 13:41:40.258625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e1c33a5eb3'
down_revision: Union[str, Sequence[str], None] = 'b5d47a980d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commandes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('prix_total', sa.Float(), nullable=False),
    sa.Column('adresse_livraison', sa.String(length=255), nullable=False),
    sa.Column('date_de_commande', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('livraison',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('service_livraison', sa.String(length=255), nullable=False),
    sa.Column('numero_commande', sa.String(length=100), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('date_expedition', sa.Date(), nullable=False),
    sa.Column('date_livraison', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_commande')
    )
    op.create_table('paiement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('montant', sa.Float(), nullable=False),
    sa.Column('moyen_paiement', sa.String(length=30), nullable=False),
    sa.Column('statut', sa.String(length=30), nullable=False),
    sa.Column('reference', sa.String(length=30), nullable=False),
    sa.Column('date_paiement', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reference')
    )
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commande_id', sa.Integer(), nullable=False),
    sa.Column('produit_id', sa.Integer(), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('quantite', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commande_id'], ['commandes.id'], ),
    sa.ForeignKeyConstraint(['produit_id'], ['produit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article')
    op.drop_table('paiement')
    op.drop_table('livraison')
    op.drop_table('commandes')
    # ### end Alembic commands ###
