"""initial migration

Revision ID: b5d47a980d9c
Revises: 
Create Date: 2026-03-08 10:06:47.470724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5d47a980d9c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marque', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('mot_de_passe', sa.String(length=255), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('date_creation', sa.Date(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('adresse',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_id', sa.Integer(), nullable=False),
    sa.Column('rue', sa.String(length=255), nullable=False),
    sa.Column('ville', sa.String(length=100), nullable=False),
    sa.Column('code_postal', sa.String(length=20), nullable=False),
    sa.Column('pays', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['utilisateur_id'], ['utilisateur.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('modele',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marque_id', sa.Integer(), nullable=False),
    sa.Column('modele', sa.String(length=100), nullable=False),
    sa.Column('date_de_sortie', sa.Date(), nullable=False),
    sa.Column('taille_ecran', sa.Float(), nullable=False),
    sa.Column('capacite_batterie', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['marque_id'], ['marque.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_modele', sa.Integer(), nullable=False),
    sa.Column('lmei', sa.String(length=20), nullable=False),
    sa.Column('stockage', sa.Integer(), nullable=False),
    sa.Column('couleur', sa.String(length=20), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('prix_de_vente', sa.Float(), nullable=False),
    sa.Column('annee_de_sortie', sa.Integer(), nullable=False),
    sa.Column('numero_de_garantie', sa.String(length=100), nullable=False),
    sa.Column('statut', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['id_modele'], ['modele.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lmei')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produit')
    op.drop_table('modele')
    op.drop_table('adresse')
    op.drop_table('utilisateur')
    op.drop_table('marque')
    # ### end Alembic commands ###
